### ISSUE TITLE
Certificate extension "critical" flag missing in encoded TBS

### ISSUE THREAD

**Issue by abgoldberg** [PeculiarVentures/pkijs-es6#18]
It appears that when a certificate is parsed into a Certificate object, and then encoded back out using `certificate.toSchema(encodeFlag)`, the extensions (Basic Constraints, Key Usage), which had the "critical" flag set in the input, no longer have that flag set in the final output. I see that critical is set to true in `Extension.toSchema` but I guess the asn1js code doesn't handle that field properly. 

It turns out, in my case, I can get around the issue by passing encodeFlag=false, so the original input tbs is used instead of re-creating it. If I don't do this, the re-created tbs doesn't match the original and the certificate signature verification fails and caused data signed by this cert to fail verification. 

Let me know if more detail, or an example, is needed. Like I said, this isn't a blocking bug for me, but it seems bad if the encoded tbs doesn't match the original (and thus doesn't match the cert's signature).

**Comment by YuryStrozhevsky** [comment]
Yes, it was an error in ASN1js. Fixed in last release.
