### ISSUE TITLE
Add SMIME encryption example

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pkijs-es6#19]
Thanks to @abgoldberg we have a working PKIjs-ES6 "S/MIME signing example" but we should also have a "S/MIME encryption example" also.

Hopefully, he can find the time to provide one as he understands the problem. Absent that it's my hope someone else can contribute such a sample.

**Comment by rmhrisk** [comment]
@abgoldberg do you think you would be able to provide this example?

**Comment by abgoldberg** [comment]
Yes, but I'm not sure when. Do you have any example encrypted messages and the corresponding private keys in a format that pkijs currently supports? My personal examples are using my own keys, and I'm using forge to parse the PKCS#12 PEM text. The mime parsing and decryption are relatively straightforward; it's this other stuff that's kind of problematic.

**Comment by rmhrisk** [comment]
I don't, but I am happy to capture some samples.

I was thinking that a sample would create keys/certs and encrypt/decrypt with them.

As for when, it's no rush, but since you have recently become the S/MIME in JS king I thought it would be great if you could provide this. :)

**Comment by abgoldberg** [comment]
Oh yeah I guess that makes sense (generating the keys/certs all in the 
example). So samples aren't really necessary. I'll try to get to this in the 
next week or two.
Sent with [inky](http://inky.com?kme=signature)

**Comment by abgoldberg** [comment]
See #25

**Comment by rmhrisk** [comment]
fixed
