### ISSUE TITLE
Typing error: CertificateSet.certificates

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/pkijs-es6#24]
What is corretct type for `CertificateSet.certificates`?
it has declared type in `constructor` as `Array` ([code](https://github.com/PeculiarVentures/pkijs-es6/blob/master/src/CertificateSet.js#L17))
But `defaultValues` returns `number` for `certificates` ([code](https://github.com/PeculiarVentures/pkijs-es6/blob/master/src/CertificateSet.js#L37))

**Comment by YuryStrozhevsky** [comment]
Fixed
