### ISSUE TITLE
EnvelopedData: Unreachable parameter

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/pkijs-es6#27]
incoming parameter `variant` in unreachable ([code](https://github.com/PeculiarVentures/pkijs-es6/blob/master/src/EnvelopedData.js#L319-L327))
it's overrided in given lines

**Comment by YuryStrozhevsky** [comment]
It would not be fixed: see [this link](https://github.com/PeculiarVentures/PKI.js/wiki/Working-with-CMS-EnvelopedData)
