### ISSUE TITLE
Typings: CMS example

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/pkijs-es6#33]
`typeval` is a `string`, but if it's undefined it has value from `AttributeTypeAndValue.type`. Type of `AttributeTypeAndValue.type` is `number` ([code](https://github.com/PeculiarVentures/pkijs-es6/blob/master/src/AttributeTypeAndValue.js#L16-L20))
- [error 1](https://github.com/PeculiarVentures/pkijs-es6/blob/master/examples/CMS%20Signed%20complex%20example/es6.js#L249-L251)
- [error 2](https://github.com/PeculiarVentures/pkijs-es6/blob/master/examples/CMS%20Signed%20complex%20example/es6.js#L281-L283)

**Comment by YuryStrozhevsky** [comment]
Fixed
