### ISSUE TITLE
Error building bundle.js for example

### ISSUE THREAD

**Issue by abgoldberg** [PeculiarVentures/pkijs-es6#4]
I tried my best guess of how to build bundle.js for the CMS signed complex example, but I get an error about resolving path "pkijs/src/common" in es6.js 

I'm new to rollup and es6 so maybe I'm missing something obvious. To setup, I ran "npm install" in the root of the checked out project, and then in the example for ran "npm run buildes6". I tried making a symlink to the pkijs root in the local sample directory, but that didn't help.

**Comment by YuryStrozhevsky** [comment]
I had just tested it and all works perfect. But please note that I put PKIjs package inside "node_modules" directory and then run "npm run buildes6" right from "CMS signed complex example" folder. Hope my note will solve your issue.

**Comment by abgoldberg** [comment]
After some experimentation, i was able to get the build to run. It seems to work with the specific version of rollup listed in package.json, but I had run into some errors using the latest rollup.
