### ISSUE TITLE
Add SMIME sample

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pkijs-es6#9]
@abgoldberg as you know in PKIjs-es5 we has an S/MIME sample (https://github.com/PeculiarVentures/PKI.js/tree/master/examples/SMIME%20example) would you be up for creating a PKIjs ES6 version laid out similarly to the other samples in https://github.com/PeculiarVentures/pkijs-es6/tree/master/examples and sending us a pull request?

**Comment by abgoldberg** [comment]
Yes I can probably do that sometime in the next week or two. I just have to remove some custom parts to make a general example.

**Comment by rmhrisk** [comment]
Thanks, that would be great.

**Comment by abgoldberg** [comment]
See pull request #16

**Comment by rmhrisk** [comment]
@abgoldberg thank you very much.

Would you also have time to extend the sample to show encryption also? The hard part, as you probably know is mime related, the rest is basically the same as : https://github.com/PeculiarVentures/pkijs-es6/blob/62bbedea4cd3b60debbdc309bc48b5c188f4504e/examples/How%20To%20Encrypt%20CMS%20via%20certificate/es6.js

**Comment by rmhrisk** [comment]
@YuryStrozhevsky can you take a look at #16 and merge as appropriate?

**Comment by YuryStrozhevsky** [comment]
I made little changes in code and append it to PKIjs. Again thank you for the support!
